### PR TITLE
Fix retrieval of input variables in hayes configuration interface

### PR DESCRIPTION
**Pull request by maltelueken**
Fixes https://github.com/jasp-stats/jasp-test-release/issues/2650

Not sure if there is a better way to fix this...

### CODE REVIEW

**Comment by shun2wang** [comment]
OK I have no access for it, you can merge it or maybe @JohnnyDoorn want to have a look.

**Comment by maltelueken** [comment]
Thanks, one unit test was still failing (which is not supposed to fail), but now it's fixed.

**Comment by shun2wang** [comment]
that's maybe what https://github.com/jasp-stats/INTERNAL-jasp/issues/2596 want to do?

**Comment by maltelueken** [comment]
I think the problem here is that the QML `VariablesList` is wrapped in a `ComponentsList`  which has the consequence that the input to are is not encoded and transformed as usual. For that reason, I need to use `[["value"]]` here because that is how the variables are stored in R. I checked this in a dev module within JASP (and also through `jaspTools`).

**Comment by JohnnyDoorn** [comment]
OK great! I see the unit tests still fail though, but you mentioned fixing them? Or were there others that are still problematic?

**Pull request merged**
