### PR TITLE
Alter the blavaan source

### PR DESCRIPTION
**Pull request by RensDofferhoff**
Was there any reason not to use blavaan from cran? @maltelueken

### CODE REVIEW

**Comment by RensDofferhoff** [comment]
The unit test numbers are ever so slightly different.
Slight difference in sampling params?
Or was this the reason to use a clone of blavaan?

**Comment by maltelueken** [comment]
I am not sure why there are these slight differences in the parameter estimates that make the Bayesian tests fail. They run fine locally. It's likely due to the sampling in Stan indeed. There is a similar issue for the classical tests on Ubuntu, also very small differences.

**Comment by RensDofferhoff** [comment]
> Previously, it wasn't possible to pin R packages to a specific version, so I used a clone. Is this possible in JASP now?

I  have finished a renv lockfile feature started by @vandenman  that allows  this.
The only known remaining issue is blavaan compilation on MacOS. 
Therefore I had hoped to pin it to precompiled CRAN binaries.

But alas. I will continue to fix the blavaan compilation.

**Comment by maltelueken** [comment]
Great! Is it not possible to pin it to 0.5-2 on CRAN then?

**Comment by RensDofferhoff** [comment]
Yes, once/if its merged!

**Comment by RensDofferhoff** [comment]
Though CRAN no longer has those binaries

**Comment by maltelueken** [comment]
Ok, but now it still pins to version 0.5-5. I am a bit confused.

**Comment by RensDofferhoff** [comment]
CRAN only keeps the binaries of the latest version.
I will remove this PR for now since we need 0.5-2 due to bugs in later versions.
We can pin it to 0.5-2 once https://github.com/jasp-stats/jasp-desktop/pull/5556 is merged

**Pull request closed without merging**
