### PR TITLE
Fix multiple small bugs (part 2)

### LINKED ISSUE #92: Bayesian Process issues
Just tried the Bayesian process analysis, but quickly ran into some issues:
- there is no runjags package
image

- dim(x) positive length when Hayes model not fully configured?

see attached jasp file (change ext)
[bayesprocerrors.zip](https://github.com/jasp-stats/jaspProcess/files/15249230/bayesprocerrors.zip)

### LINKED ISSUE #93: Freq Process - bootstrap + local tests do not work?
I just encountered some more issues with the process module when running bootstrap (setting for all models does not seem to affect any of the output?) and local tests (gives error below)
image

[video_games.zip](https://github.com/jasp-stats/jaspProcess/files/15249333/video_games.zip)

### LINKED ISSUE #94: when having multiple IV’s, the legend with labels does not show all the IV’s properly aligned
when having multiple IV’s, the legend with labels does not show all the IV’s properly aligned

image

I used the classical process module

### LINKED ISSUE #95: when plotting and showing both labels and colors as legend, would be nice to have the same order so that one can match color with variable type
when plotting and showing both labels and colors as legend to the conceptual and statistical path plots, would be nice to have the same order so that one can match color with variable type

image

### PR DESCRIPTION
**Pull request by maltelueken**
Fixes #92 by calling `lavaan::sem` instead of `blavaan::bsem` to only build the model instead of fitting it when the input is incomplete.
Fixes #93 by removing a skip logic so that dummy and interaction variables are always added to the data set (and not only if models are recomputed).
Fixes #94
Fixes #95 

Also adds tests to check if the analysis runs when a Hayes configuration is incomplete (see #92).

### CODE REVIEW

**Comment by JohnnyDoorn** [comment]
The most recent nightly doesn't have working dev modules I believe - do you use a specific version to test it for yourself?

**Comment by maltelueken** [comment]
Yes, I am using `development-a662d7970e45325a6cbab59429d1d649141a6058` from 08-05.

**Comment by JohnnyDoorn** [comment]
There seems to be an issue with the qml - the forms fall off:
image

and with https://github.com/jasp-stats/jasp-desktop/commit/6b20ac88b09040c0706a02f4db107f62ebb7d812 Im still getting an error about 
```
Error: .onLoad failed in loadNamespace() for 'jaspJags', details:
  call: loadNamespace(x)
  error: there is no package called ‘runjags’
```
It happens with bayesian process, after running for a while...

For the rest it looks awesome!

**Comment by JohnnyDoorn** [comment]
Also, the statistical path plots do not seem to have the path letters/numbers anymore, or the estimates when asked (seems to happen with any data/model)
image
although it seems like a state-issue (refreshing helps)
[bronstein_2019_nolabels.zip](https://github.com/jasp-stats/jaspProcess/files/15348411/bronstein_2019_nolabels.zip)

**Comment by maltelueken** [comment]
I fixed both the cutting off and the missing path labels. I also added `runjags` as an explicit import. @JohnnyDoorn, could you test if this fixes the loading issue on Mac?

**Comment by JohnnyDoorn** [comment]
Awesome, that worked!

**Review by JohnnyDoorn — APPROVED** [review]

**Comment by JohnnyDoorn** [comment]
Does @ThijsVroegh also want to review this? Or shall I merge?

**Comment by maltelueken** [comment]
This can be merged!

**Pull request merged**
