### PR TITLE
Change standardized effect estimation to model-based approach

### PR DESCRIPTION
**Pull request by maltelueken**
Previously, standardized estimates were computed by standardizing the variables before entering the analysis. This, however, can lead to biased results for some models and didn't allow estimating standardized and unstandardized effects at the same time. Instead, standardized effects are now estimated using the model-implied covariance matrix and added to the output tables of the unstandardized effects.

The UI elements for mean-centering and standardized estimates are now check boxes instead of a radio button group, so users can request both at the same time (mean-centering obviously only applies to unstandardized estimates).

Represent two-way interactions as product variables (same as three-way interactions), e.g., `var1__var2` instead of `var1:var2`, because the mean-centering is different and the new approach provides results closer to PROCESS. Mean-centering is applied before the product variables are computed.

Previously, mean-centering was applied to all model variables, now it is only applied to variables involved in interactions (as in PROCESS).

Fixes a bug when a moderated moderation with a multi-level factor was specified.

For all, auto-generated tests, I added standardized estimates to the output.

### CODE REVIEW

**Comment by maltelueken** [comment]
The tests that fail also fail in the master branch. I am not exactly sure why since they run fine locally for me. There have been multiple issues with running the tests on the GitHub Action servers lately (some of which disappeared after some time).

**Comment by JohnnyDoorn** [comment]
@maltelueken - looks good so far! will test a bit more elaborately later. Do i see correctly that the unit tests remain unchanged (except the plots and input options)? And if so, do you have any verified example to go along with this that you can make a unit test out of?

**Comment by maltelueken** [comment]
Sorry for the delayed response! I change the standardization procedure slightly to align with the approach in the manymome package and what the recent literature recommends (see [this](https://link.springer.com/article/10.3758/s13428-023-02224-z) paper). Interaction effects are still standardized by the model-implied standard deviation of all interacting terms, making them interpretable as standardized moderation effects. Conditional direct and indirect effects, however, are only standardized by the implied SD of X and Y (not M or any moderators). This should make these standardized effects easier to interpret.

I also added two verification tests that compare the output to results from Hayes book and those obtained by the manymome package (which uses the same approach as the Process module).

@JohnnyDoorn, the unit tests are indeed the same except that standardized effects are added to all tables. There are new plots to test for a special case with moderated moderation where the first moderator is a three-level factor. The tests run fine locally but are failling on GitHub due to a reason I couldn't figure out so far (but they also fail on the master branch, so it's likely not due to changes in this PR). Could you perhaps also look at the section in the help file about standardized effects and check if it is understandable?

**Comment by JohnnyDoorn** [comment]
@maltelueken will do! Is there any rng in the unit tests? because that could be causing some issues (even with seed setting - we've had similar issues with anova).

**Comment by maltelueken** [comment]
There are some unit tests for which rng dummy data is used, but those are not the ones failing. The failing tests are due to changes in some plots, but when I create the plots locally, they look exactly as they should and the tests pass. The PR also doesn't change anything related to the plotting.

**Comment by JohnnyDoorn** [comment]
So I played around a bit with the module, and found a couple of strange bugs/non-informative error messages - see the attached zip file with 3 .jasp files that give errors, can you reproduce those? 
I also saw that when you add a model, it messes up the qml of the previous model: the options menu gets cut off:
image

**Comment by maltelueken** [comment]
I think the zip file is missing! I will make a new issue for the QML and ask Bruno to take a look because I think it's related to the component itself.

**Comment by maltelueken** [comment]
This is the issue for the QML bug: https://github.com/jasp-stats/jasp-issues/issues/2661

**Comment by JohnnyDoorn** [comment]
Ah sorry, it's there now

**Comment by maltelueken** [comment]
Thanks! I could reproduce bug 1 and 3, but not 2 (I suspect that might be an issue related to the TabView QML component). I fixed these two bugs and an additional one which occurred for me instead of bug 2.

**Review by JohnnyDoorn — APPROVED** [review]

**Comment by JohnnyDoorn** [comment]
One last question - why did you choose to use "__" for interactions instead of ":"? Because the latter is more consistent with the rest of JASP - did it break some other code?

**Comment by maltelueken** [comment]
> One last question - why did you choose to use "__" for interactions instead of ":"? Because the latter is more consistent with the rest of JASP - did it break some other code?

The reason is that the interaction terms are computed as separate variables before they are entered into lavaan. There are multiple reasons for this:

- Computing the interactions with `:` in the lavaan syntax leads to different results (not the results users would expect)
- Moderation effects must be mean-centered before entering variables in lavaan
- lavaan cannot compute three-way interactions through the syntax, so they need to be expressed these through precomputed variables

To use variables that represent interaction terms in the lavaan syntax, we cannot use `:` in the variable name, so I chose `__` instead.

**Pull request merged**
